name: GoogleTest CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build

    - name: Build
      run: |
        cd ${{github.workspace}}/build
        cmake ..
        make

    - name: Test
      run: |
        cd ${{github.workspace}}/build
        ctest
