name: GoogleTest CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build

    - name: Build
      run: |
        cd ${{github.workspace}}/build
        cmake ..
        make

    - name: Test
      run: |
        cd ${{github.workspace}}/build
        ./workinghours_calculator_test

    - name: Execute gcov
      run: |
        cd ${{github.workspace}}/build/CMakeFiles/workinghours_calculator_lib.dir/src
        gcov *.gcda

    - name: Generate Coverage Report
      uses: danielpalme/ReportGenerator-GitHub-Action@5.2.0
      with:
        reports: ${{github.workspace}}/build/CMakeFiles/workinghours_calculator_lib.dir/src/*.gcov
        targetdir: CoverageReport
        reporttypes: Html;MarkdownSummaryGithub;Badges

    - name: Upload Coverage Report
      uses: actions/upload-artifact@v3
      with:
        name: coverage-report
        path: ./CoverageReport

    - name: Add Coverage Report To PR Comment
      uses: marocchino/sticky-pull-request-comment@v2
      if: github.event_name == 'pull_request'
      with:
        recreate: true
        path: CoverageReport/SummaryGithub.md
